name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # File filtering for efficiency - only Python and config files
    paths:
      - "src/**/*.py"
      - "tests/**/*.py"
      - "poc/**/*.py"
      - "**/*.toml"
      - "**/*.txt"
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  claude-review:
    # Conditional execution for efficiency - skip drafts and WIP
    if: |
      !github.event.pull_request.draft &&
      !contains(github.event.pull_request.title, '[skip-review]') &&
      !contains(github.event.pull_request.title, '[WIP]') &&
      !contains(github.event.pull_request.title, 'WIP:')
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # MCP-focused comprehensive review prompt
          direct_prompt: |
            Проведите комплексный код-ревью этого Pull Request для проекта MCPISIA (MCP implementation):

            **Основной фокус:**
            - 🔒 Безопасность: валидация входных данных, санитизация путей, предотвращение path traversal
            - 🏗️ Архитектура MCP: соответствие протоколу MCP, правильность tool definitions
            - ⚡ Производительность: async/await паттерны, эффективность memory operations
            - 🧪 Качество тестов: покрытие, edge cases, моки для Redis
            - 📝 Документация: docstrings на русском, type hints

            **Специфичные проверки:**
            - Filesystem operations: sandboxing, размер файлов, разрешенные расширения
            - Memory component: TTL корректность, Redis fallback logic
            - Error handling: comprehensive but user-friendly
            - PEP 8 соответствие и код стиль

            Предоставьте конкретные рекомендации с примерами кода где необходимо.

          # Efficiency optimization - sticky comments
          use_sticky_comment: true
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Python development tools for comprehensive analysis
          allowed_tools: |
            Bash(python -m pytest*),
            Bash(python -m black*),
            Bash(python -m flake8*),
            Bash(python -m mypy*),
            Bash(python -m isort*),
            Bash(python -m coverage*),
            Bash(git*), Bash(ls*), Bash(cat*), Bash(grep*)
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

